INSERT INTO products (nome, preco, marca, descricao, status) VALUES
('Smartphone Galaxy S23 128GB AMOLED', 4299.90, 'Samsung',
 'Smartphone Samsung Galaxy S23 com tela AMOLED, desempenho avançado e câmeras de alta qualidade.',
 'ACTIVE'),
('Smartphone Galaxy S23 256GB AMOLED', 4799.90, 'Samsung',
 'Smartphone Samsung Galaxy S23 com maior capacidade de armazenamento e excelente desempenho para uso diário.',
 'ACTIVE'),
('Smartphone Galaxy S23 Ultra 512GB AMOLED', 6899.90, 'Samsung',
 'Versão Ultra do Galaxy S23 com armazenamento ampliado, câmera profissional e tela premium.',
 'ACTIVE'),
('Smart TV LED 50 Polegadas 4K', 2699.90, 'LG',
 'Smart TV LG 4K com cores vivas, sistema inteligente e ótima qualidade de imagem para filmes e séries.',
 'ACTIVE'),
('Smart TV LED 55 Polegadas 4K', 3199.90, 'LG',
 'Televisor LG com resolução 4K, conectividade Wi-Fi e experiência imersiva para entretenimento.',
 'ACTIVE'),
('Smart TV OLED 65 Polegadas 4K', 5999.90, 'LG',
 'Smart TV OLED LG com contraste infinito, pretos perfeitos e tecnologia avançada de imagem.',
 'ACTIVE'),
('Geladeira Frost Free 375L Inox', 3899.90, 'Brastemp',
 'Geladeira Brastemp Frost Free com design moderno, boa capacidade interna e economia de energia.',
 'ACTIVE'),
('Geladeira Frost Free 400L Inox', 4299.90, 'Brastemp',
 'Refrigerador Brastemp com maior capacidade, prateleiras ajustáveis e tecnologia Frost Free.',
 'ACTIVE'),
('Geladeira Frost Free 462L Inox', 4999.90, 'Brastemp',
 'Geladeira Brastemp espaçosa, ideal para famílias grandes, com excelente organização interna.',
 'ACTIVE'),
('Máquina de Lavar 11kg Automática', 2499.90, 'Electrolux',
 'Lavadora Electrolux automática com capacidade de 11kg e diversos programas de lavagem.',
 'ACTIVE'),
('Máquina de Lavar 13kg Automática', 2899.90, 'Electrolux',
 'Lavadora Electrolux com maior capacidade, economia de água e lavagem eficiente.',
 'ACTIVE'),
('Máquina de Lavar 15kg Automática', 3399.90, 'Electrolux',
 'Máquina de lavar Electrolux ideal para grandes volumes de roupa, com alta performance.',
 'ACTIVE'),
('Aspirador de Pó PowerGo 1400W', 699.90, 'Philips',
 'Aspirador de pó Philips com potência de 1400W, eficiente para limpeza diária.',
 'ACTIVE'),
('Aspirador de Pó PowerGo 1800W', 899.90, 'Philips',
 'Aspirador Philips mais potente, ideal para limpeza profunda de diferentes superfícies.',
 'ACTIVE'),
('Aspirador de Pó PowerPro 2000W', 1199.90, 'Philips',
 'Aspirador de pó Philips PowerPro com alta potência e sistema avançado de filtragem.',
 'ACTIVE'),
('Ventilador de Mesa 30cm', 179.90, 'Mondial',
 'Ventilador de mesa Mondial compacto, silencioso e eficiente para ambientes pequenos.',
 'ACTIVE'),
('Ventilador de Mesa 40cm', 229.90, 'Mondial',
 'Ventilador Mondial com maior diâmetro, proporcionando melhor circulação de ar.',
 'ACTIVE'),
('Ventilador de Coluna 40cm', 299.90, 'Mondial',
 'Ventilador de coluna Mondial ajustável, ideal para refrescar ambientes maiores.',
 'ACTIVE'),
('Liquidificador Power Max 700W', 249.90, 'Arno',
 'Liquidificador Arno com potência de 700W, ideal para sucos, vitaminas e massas leves.',
 'ACTIVE'),
('Liquidificador Power Max 900W', 319.90, 'Arno',
 'Liquidificador Arno mais potente, indicado para preparo rápido de diversas receitas.',
 'ACTIVE'),
('Liquidificador Power Mix 1000W', 389.90, 'Arno',
 'Liquidificador Arno de alta potência, perfeito para receitas pesadas e uso frequente.',
 'ACTIVE'),
('Notebook Intel Celeron 4GB 128GB SSD', 2199.90, 'Positivo',
 'Notebook Positivo para tarefas básicas, com armazenamento SSD e bom desempenho diário.',
 'ACTIVE'),
('Notebook Intel Celeron 8GB 256GB SSD', 2599.90, 'Positivo',
 'Notebook Positivo com memória ampliada, ideal para estudos e trabalho.',
 'ACTIVE'),
('Notebook Intel Core i3 8GB 256GB SSD', 3199.90, 'Positivo',
 'Notebook Positivo com processador Core i3, oferecendo melhor desempenho multitarefa.',
 'ACTIVE'),
('Conjunto de Panelas Inox 5 Peças', 699.90, 'Tramontina',
 'Conjunto de panelas Tramontina em inox, durável e ideal para uso diário.',
 'ACTIVE'),
('Conjunto de Panelas Inox 7 Peças', 899.90, 'Tramontina',
 'Conjunto de panelas Tramontina com mais opções de preparo e excelente acabamento.',
 'ACTIVE'),
('Conjunto de Panelas Inox 9 Peças', 1199.90, 'Tramontina',
 'Conjunto completo de panelas Tramontina, ideal para cozinhas modernas.',
 'ACTIVE'),
('Micro-ondas 20L Branco', 549.90, 'Consul',
 'Micro-ondas Consul compacto, fácil de usar e ideal para o dia a dia.',
 'ACTIVE'),
('Micro-ondas 25L Branco', 699.90, 'Consul',
 'Micro-ondas Consul com maior capacidade e funções práticas para aquecimento.',
 'ACTIVE'),
('Micro-ondas 32L Inox', 899.90, 'Consul',
 'Micro-ondas Consul em inox, espaçoso e com design moderno para a cozinha.',
 'ACTIVE');